# Feature Engineering

---

1. Import packages
2. Load data
3. Feature engineering

---

## 1. Import packages

In [1]:
import pandas as pd

---
## 2. Load data

In [3]:
df = pd.read_csv('C://Users//pooja//Downloads//BCG JobSimulation Data//clean_data_after_eda.csv')
df["date_activ"] = pd.to_datetime(df["date_activ"], format='%Y-%m-%d')
df["date_end"] = pd.to_datetime(df["date_end"], format='%Y-%m-%d')
df["date_modif_prod"] = pd.to_datetime(df["date_modif_prod"], format='%Y-%m-%d')
df["date_renewal"] = pd.to_datetime(df["date_renewal"], format='%Y-%m-%d')

In [3]:
df.head(3)

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,0.000131,4.100838e-05,0.000908,2.086294,99.530517,44.235794,2.086425,9.953056e+01,44.236702,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.000003,1.217891e-03,0.000000,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0.000004,9.450150e-08,0.000000,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14606 non-null  str
 1   channel_sales                   14606 non-null  str
 2   cons_12m                        14606 non-null  int64
 3   cons_gas_12m                    14606 non-null  int64
 4   cons_last_month                 14606 non-null  int64
 5   date_activ                      14606 non-null  datetime64[us]
 6   date_end                        14606 non-null  datetime64[us]
 7   date_modif_prod                 14606 non-null  datetime64[us]
 8   date_renewal                    14606 non-null  datetime64[us]
 9   forecast_cons_12m               14606 non-null  float64
 10  forecast_cons_year              14606 non-null  int64
 11  forecast_discount_energy        14606 non-null  float64
 12  forecast_meter_rent_12m         14606 non-null  float64
 13  forecast_price_energy_off_peak  14606 non-null  float64
 14  forecast_price_energy_peak      14606 non-null  float64
 15  forecast_price_pow_off_peak     14606 non-null  float64
 16  has_gas                         14606 non-null  str
 17  imp_cons                        14606 non-null  float64
 18  margin_gross_pow_ele            14606 non-null  float64
 19  margin_net_pow_ele              14606 non-null  float64
 20  nb_prod_act                     14606 non-null  int64
 21  net_margin                      14606 non-null  float64
 22  num_years_antig                 14606 non-null  int64
 23  origin_up                       14606 non-null  str
 24  pow_max                         14606 non-null  float64
 25  var_year_price_off_peak_var     14606 non-null  float64
 26  var_year_price_peak_var         14606 non-null  float64
 27  var_year_price_mid_peak_var     14606 non-null  float64
 28  var_year_price_off_peak_fix     14606 non-null  float64
 29  var_year_price_peak_fix         14606 non-null  float64
 30  var_year_price_mid_peak_fix     14606 non-null  float64
 31  var_year_price_off_peak         14606 non-null  float64
 32  var_year_price_peak             14606 non-null  float64
 33  var_year_price_mid_peak         14606 non-null  float64
 34  var_6m_price_off_peak_var       14606 non-null  float64
 35  var_6m_price_peak_var           14606 non-null  float64
 36  var_6m_price_mid_peak_var       14606 non-null  float64
 37  var_6m_price_off_peak_fix       14606 non-null  float64
 38  var_6m_price_peak_fix           14606 non-null  float64
 39  var_6m_price_mid_peak_fix       14606 non-null  float64
 40  var_6m_price_off_peak           14606 non-null  float64
 41  var_6m_price_peak               14606 non-null  float64
 42  var_6m_price_mid_peak           14606 non-null  float64
 43  churn                           14606 non-null  int64
dtypes: datetime64[us](4), float64(29), int64(7), str(4)
memory usage: 4.9 MB

---

## 3. Feature engineering

### Difference between off-peak prices in December and preceding January

In [4]:
price_df = pd.read_csv('C://Users//pooja//Downloads//BCG JobSimulation Data//price_data.csv')
price_df["price_date"] = pd.to_datetime(price_df["price_date"], format='%Y-%m-%d')
price_df.head()

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0

In [6]:
# Group off-peak prices by companies and month
monthly_price_by_id = price_df.groupby(['id', 'price_date']).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()

# Get january and december prices
jan_prices = monthly_price_by_id.groupby('id').first().reset_index()
dec_prices = monthly_price_by_id.groupby('id').last().reset_index()

# Calculate the difference
diff = pd.merge(dec_prices.rename(columns={'price_off_peak_var': 'dec_1', 'price_off_peak_fix': 'dec_2'}), jan_prices.drop(columns='price_date'), on='id')
diff['offpeak_diff_dec_january_energy'] = diff['dec_1'] - diff['price_off_peak_var']
diff['offpeak_diff_dec_january_power'] = diff['dec_2'] - diff['price_off_peak_fix']
diff = diff[['id', 'offpeak_diff_dec_january_energy','offpeak_diff_dec_january_power']]
diff.head()

,id,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,0002203ffbb812588b632b9e628cc38d,-0.006192,0.162916
1,0004351ebdd665e6ee664792efc4fd13,-0.004104,0.177779
2,0010bcc39e42b3c2131ed2ce55246e3c,0.050443,1.500000
3,0010ee3855fdea87602a5b7aba8e42de,-0.010018,0.162916
4,00114d74e963e47177db89bc70108537,-0.003994,-0.000001

## Average Monthly Consuption:

In [6]:
# Drop irrelevant columns
df = df.drop(columns=['id'])

# One-hot encode categorical columns
df = pd.get_dummies(df, columns=['channel_sales', 'origin_up', 'has_gas'])

# Extract features from date columns
df['year_activ'] = df['date_activ'].dt.year
df['month_activ'] = df['date_activ'].dt.month
df['days_active'] = (pd.to_datetime('today') - df['date_activ']).dt.days

# Calculate average monthly consumption
df['avg_monthly_consumption'] = df['cons_12m'] / 12

# Calculate tenure-related features
df['tenure_years'] = df['num_years_antig']

# Create ratios and combined features
df['consumption_ratio'] = df['cons_last_month'] / (df['cons_12m'] + 1)
df['margin_ratio'] = df['margin_net_pow_ele'] / (df['margin_gross_pow_ele'] + 1)

# Drop the original date columns
df = df.drop(columns=['date_activ', 'date_end', 'date_modif_prod', 'date_renewal'])

# Display the first few rows of the transformed DataFrame
print(df.head())

   cons_12m  cons_gas_12m  cons_last_month  forecast_cons_12m  \
0         0         54946                0               0.00
1      4660             0                0             189.95
2       544             0                0              47.96
3      1584             0                0             240.04
4      4425             0              526             445.75

   forecast_cons_year  forecast_discount_energy  forecast_meter_rent_12m  \
0                   0                       0.0                     1.78
1                   0                       0.0                    16.27
2                   0                       0.0                    38.72
3                   0                       0.0                    19.83
4                 526                       0.0                   131.73

   forecast_price_energy_off_peak  forecast_price_energy_peak  \
0                        0.114481                    0.098142
1                        0.145711                    0.000000
2                        0.165794                    0.087899
3                        0.146694                    0.000000
4                        0.116900                    0.100015

   forecast_price_pow_off_peak  ...  \
0                    40.606701  ...
1                    44.311378  ...
2                    44.311378  ...
3                    44.311378  ...
4                    40.606701  ...

   origin_up_usapbepcfoloekilkwsdiboslwaxobdp  has_gas_f  has_gas_t  \
0                                       False      False       True
1                                       False       True      False
2                                       False       True      False
3                                       False       True      False
4                                       False       True      False

   year_activ  month_activ  days_active  avg_monthly_consumption  \
0        2013            6         4619                 0.000000
1        2009            8         6013               388.333333
2        2010            4         5775                45.333333
3        2010            3         5792               132.000000
4        2010            1         5868               368.750000

   tenure_years  consumption_ratio  margin_ratio
0             3           0.000000      0.962179
1             6           0.000000      0.942463
2             6           0.000000      0.966216
3             6           0.000000      0.967969
4             6           0.118843      0.978218

[5 rows x 59 columns]